import { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import SideMenu from "../components/Menu";
import NavBar from "../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex">
      {/* left */}
      <div className="w-[18%] md:w-[25%] lg:w-[25%] xl:w-[20%] bg-slate-300 text-black p-4">
        <Link href="/" className="flex items-center justify-center gap-2 " />
        <img src="/logo.png" alt="logo" width={30} height={30} />
        <span className="hidden md:block">Reconcilation System</span>

        <div className="menuItems">
          <SideMenu></SideMenu>
        </div>
      </div>

      <div className="w-[92%] md:w-[75%] lg:w-[75%] xl:w-[80%] bg-blue-100">
        <NavBar/> 
        {children}
      </div>
    </div>
  );
}
